# Default values for catalog-server.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of catalog-server replicas to deploy
replicaCount: 2

image:
  # -- catalog-server image repository
  repository: radarbase/radar-schemas-tools
  # -- catalog-server image tag (immutable tags are recommended)
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.7.4
  # -- catalog-server image pull policy
  pullPolicy: IfNotPresent

# -- Docker registry secret names as an array
imagePullSecrets: []

# -- String to partially override catalog-server.fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override catalog-server.fullname template with a string
fullnameOverride: ""

# -- Configure catalog-server pods' Security Context
podSecurityContext: {}
  # fsGroup: 2000

# -- Configure Appconfig containers' Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- catalog-server port
  port: 9010

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # -- CPU/Memory resource limits
  # limits:
  #   cpu: 200m
  #   memory: 512Mi
  # -- CPU/Memory resource requests
  requests:
    cpu: 100m
    memory: 256Mi

persistence:
  # -- Enable persistence using PVC
  enabled: false
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  # existingClaim: your-claim
  # -- PVC Access Mode for catalog-server volume
  accessMode: ReadWriteOnce
  # -- PVC Storage Request for catalog-server volume
  size: 5Mi

# -- Node labels for pod assignment
nodeSelector: {}

# -- Toleration labels for pod assignment
tolerations: []

# -- Affinity labels for pod assignment
affinity: {}

# -- number of Kafka brokers to look for
kafka_num_brokers: 3
# -- URI of Kafka brokers
kafka: cp-kafka-headless:9092
# -- URL of the confluent schema registry
schema_registry: http://cp-schema-registry:8081

# -- List of paths of specifications relative to specifications folder, if any of the specifications should be excluded from automatically registering topics and schemas.
specificationsExclude:
# - active/*
# - passive/*1.0.0*

cc:
  # -- set to true if using Confluent Cloud for kafka cluster and schema registry
  enabled: false
  # -- URL of the bootstrap server of Confluent Cloud based kafka cluster
  bootstrapServerurl: confluent-url
  # -- API key of the Confluent Cloud based kafka cluster
  apiKey: ccApikey
  # -- API secret of the Confluent Cloud based kafka cluster
  apiSecret: ccApiSecret
  # -- API key of the Confluent Cloud based schema registry
  schemaRegistryApiKey: srApiKey
  # -- API secret of the Confluent Cloud based schema registry
  schemaRegistryApiSecret: srApiSecret
