# Default values for radar-gateway.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of radar-gateway replicas to deploy
replicaCount: 2

image:
  # -- radar-gateway image repository
  repository: radarbase/radar-gateway
  # -- radar-gateway image tag (immutable tags are recommended)
  # Overrides the image tag whose default is the chart appVersion.
  tag: 0.5.7
  # -- radar-gateway image pull policy
  pullPolicy: IfNotPresent

# -- Docker registry secret names as an array
imagePullSecrets: []

# -- String to partially override radar-gateway.fullname template with a string (will prepend the release name)
nameOverride: ""
# -- String to fully override radar-gateway.fullname template with a string
fullnameOverride: ""

# -- Configure radar-gateway pods' Security Context
podSecurityContext: {}
  # fsGroup: 2000

# -- Configure radar-gateway containers' Security Context
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- radar-gateway port
  port: 8080

ingress:
  # -- Enable ingress controller resource
  enabled: true
  # -- Annotations that define default ingress class, certificate issuer and deny access to sensitive URLs
  # @default -- check values.yaml
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /kafka/$1
    nginx.ingress.kubernetes.io/server-snippet: |
      location ^~ /kafka/consumers {
        deny all;
      }
      location ^~ /kafka/brokers {
        deny all;
      }
      location ~* /kafka/topics/.+/partitions {
        deny all;
      }
  # -- Path within the url structure
  path: "/kafka/?(.*)"
  # -- Hosts to accept requests from
  hosts:
    - localhost
  tls:
    # -- Name of the secret that contains TLS certificates
    secretName: radar-base-tls

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi

  # -- CPU/Memory resource requests
  requests:
    cpu: 100m
    memory: 128Mi

# -- Node labels for pod assignment
nodeSelector: {}

# -- Toleration labels for pod assignment
tolerations: []

# -- Affinity labels for pod assignment
affinity: {}

serviceMonitor:
  # -- Enable metrics to be collected via Prometheus-operator
  enabled: true

# -- Host name of the management portal application
managementportalHost: management-portal
# -- Schema Registry URL
schemaRegistry: http://cp-schema-registry:8081
# -- Not used. To be confirmed
max_requests: 1000
# -- Kafka broker URLs
bootstrapServers: cp-kafka-headless:9092
# -- set to true, if sources in access token should be validated
checkSourceId: true
# -- Additional Kafka Admin Client settings as key value pairs. Read from https://kafka.apache.org/documentation/#adminclientconfigs.
adminProperties: {}
# -- Kafka producer properties as key value pairs. Read from https://kafka.apache.org/documentation/#producerconfigs.
producerProperties:
  compression.type: lz4
# -- Additional Kafka serialization settings, used in KafkaAvroSerializer. Read from [io.confluent.kafka.serializers.AbstractKafkaSchemaSerDeConfig].
serializationProperties: {}

cc:
  # -- set to true, if requests should be forwarded to Confluent Cloud based brokers.
  enabled: false
  # -- Confluent Cloud cluster API key
  apiKey: ccApikey
  # -- Confluent Cloud cluster API secret
  apiSecret: ccApiSecret
  # -- Confluent Cloud schema registry API key
  schemaRegistryApiKey: srApiKey
  # -- Confluent Cloud schema registry API secret
  schemaRegistryApiSecret: srApiSecret
